name: xarray-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - bottleneck
  - numpydoc
  - matplotlib
  - seaborn
  - dask
  - ipython
  - netCDF4
  - cartopy
  - rasterio
  - zarr
  - iris
  - flake8
  - cftime
  - mock
  - pillow
  - sphinx
  - sphinx-gallery
  - sphinx_rtd_theme
